#!/bin/sh
#cd "${0%/*}" || exit                                # Run from this directory
#. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#cleancase
#------------------------------------------------------------------------------
#this was the original allclean script for icofoam cases.
#keepCases="cavity cavityGrade cavityClipped"
#loseCases="cavityFine cavityHighRe"

#for caseName in $keepCases
#do
 #   ( cd $caseName && foamCleanTutorials )
#done

#for caseName in $loseCases
#do
 #   removeCase $caseName
#done
